[package]
name = "rusty-snake"
version = "0.2.0"
authors = ["GOKOP <igorbugajski@protonmail.com>"]
edition = "2018"

[dependencies]
rand = "0.7"
clap = "2.32"

[dependencies.pancurses]
version = "0.16"
features = ["wide"]
